name: manage-azure-policy-629f2420
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Function_App_should_only_be_accessible_over_HTTPS_6d555dd1-86f2-4f1c-8ed7-5abae7c6cbab/**'
#      - .github/workflows/manage-azure-policy-629f2420.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_629f2420}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Function_App_should_only_be_accessible_over_HTTPS_6d555dd1-86f2-4f1c-8ed7-5abae7c6cbab/**
